- src/app/constants.ts
https://trello.com/c/Kf9ayPZ3/6699-qa-signin-unable-to-use-https-or-http-full-url-as-username
> accept x lowercase in orcid id and remove http(s) from regex

- src/app/constants.ts
- src/app/core/sign-in/sign-in.service.ts
- src/app/shared/validators/username/username.validator.ts
https://trello.com/c/Kf9ayPZ3/6699-qa-signin-unable-to-use-https-or-http-full-url-as-username
> fix username validation

- src/app/sign-in/components/two-factor/two-factor.component.html
- src/app/sign-in/components/two-factor/two-factor.component.scss
https://trello.com/c/r0gAeSRZ/6725-qa-signin-2fa-character-counter-disappears-when-error-message-is-displayed
> Display length of authentication and recovery code in mat error

- src/app/sign-in/pages/sign-in/sign-in.component.html
- src/app/sign-in/pages/sign-in/sign-in.component.ts
https://trello.com/c/av77gGht/6787-qa-signin-password-should-not-be-required-for-unclaimed-and-deactivated-records
> Remove password validator

- src/app/institutional/pages/institutional/institutional.component.html
- src/app/institutional/pages/institutional/institutional.component.scss
https://trello.com/c/BOFJNdAv/6803-qa-signin-institutional-signin-go-back-button-is-not-aligned-properly-on-ie11
> Fix go back button institutional sign in

- src/assets/scss/material.light-theme.scss
- src/assets/scss/material.orcid.overwrites.scss/_form-field-outline-theme.scss
- src/styles.scss
Add a new color to the background theme and overwrites chrome and edge input autofill colors
> Overwrite chrome and edge input autofill colors

- src/app/register/components/form-personal/form-personal.component.html
**Coping the same last message a put on the Trello card here:**
Unfortunately, disabling this is not really a supported feature on any major browser 
https://caniuse.com/#feat=input-autocomplete-onoff, and there are many open discussions about
why and why not should browsers allow developers to disable autocompletes...
And there is a lot of info about why the "retype email" is bad UX...
But to avoid going too deep with this one, I would like to try one more thing that seems
to be working for me.
> Atemp to disable autocompletes on email confirmation

- cypress/helpers/date.js
- cypress/integration/registry/01. Release QA.js
- add function to get hyphen separated date with hour and minutes to easily run the tests multiple times the same day
- bypass the server call to check for duplicated accounts, and focus this test only on the register feature
- test the get().within()  cypress feature functions to avoid relying on the visibility
- avoid relying on hardwired `waits` and use `.ng-valid` class to wait for async validations on each step
> Add some features

- src/app/sign-in/components/logged-in/logged-in.component.html
- src/assets/scss/material.orcid.overwrites.scss/button.scss
https://trello.com/c/4vRV7MNY/6819-qa-signin-continue-as-account-name-button-cant-handle-long-names
> Add mat button wrap

- src/app/layout/header/menu.ts
https://trello.com/c/vhIi0EWh/6924-for-researchers-menu-link-goes-to-different-pages-depending-on-what-site-youre-on-when-you-click-it
> fix `For Researchers` menu link

- src/app/link-account/pages/link-account/link-account.component.ts
https://trello.com/c/jqTMpxiE/6939-qa-toaster-shown-in-signin-after-returning-from-social-linking
> fix toaster showed after cancel button is pressed in link account

- src/app/core/sign-in/sign-in.service.ts
- src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
- src/app/types/sign-in.local.ts
https://trello.com/c/XKE9EG4n/7009-qa-oauth-institutional-social-linking-doesnt-take-effect
> fix qa oauth institutional social linking

- src/app/authorize/pages/authorize/authorize.component.html
https://trello.com/c/F4kod5eF/6997-qa-oauth-orcid-id-should-be-displayed-as-full-url
> fix oauth ORCID id url

- src/app/guards/sign-in.guard.ts
- src/app/register/pages/register/register.component.ts
https://trello.com/c/UklUsRR3/6978-qa-authorization-url-with-email-address-that-doesnt-exist-in-the-db-should-display-the-register-screen
> fix oauth redirect to register form if email doesnt exists

- src/app/guards/sign-in.guard.ts
https://trello.com/c/qbSLbU6R/6979-qa-authorization-url-with-orcid-id-that-doesnt-exist-should-display-register-screen
> fix oauth redirect to register if orcid id doesnt exist in db

- package-lock.json
- package.json
- src/polyfills.ts
fix URLSearchParams in ie11 and upgrade to core-js@3 since core-js@2 is obsolete
> fix urlsearchparams in ie11

- README.md
- src/app/sign-in/pages/sign-in/sign-in.component.ts
https://trello.com/c/17aZIHRL/7056-email-is-not-filled-in-sign-in-page-after-you-tried-to-register-an-email-is-already-in-the-db-and-clicked-sign-in-this-email-alr
> fix email is not filled in sign in page

- src/app/cdk/info-drop-down/info-drop-down.component.html
- src/app/register/components/form-password/form-password.component.html
- src/app/register/components/form-personal-additional-emails/form-personal-additional-emails.component.html
- src/app/register/components/form-personal/form-personal.component.html
- src/app/register/components/step-a/step-a.component.ts
https://trello.com/c/wSs4iTnB/7027-qa-sandbox-sign-in-register-and-oauth-using-old-help-icons
> fix info icon

- src/app/register/components/step-a/step-a.component.ts
https://trello.com/c/wqPV0PTV/7089-remove-showlogin-parameter-in-oauth-request-if-the-user-clicks-sign-in
> remove show login parameter

- src/app/cdk/info-drop-down/info-drop-down.component.html
- src/app/cdk/info-drop-down/info-drop-down.component.scss
- src/app/register/components/form-password/form-password.component.html
- src/app/register/components/form-personal-additional-emails/form-personal-additional-emails.component.html
- src/app/register/components/form-personal/form-personal.component.html
- src/styles.scss
https://trello.com/c/wSs4iTnB/7027-qa-sandbox-sign-in-register-and-oauth-using-old-help-icons
> fix help icon size

- src/app/core/inbox/inbox.service.ts
- src/app/inbox/components/notification/notification.component.scss
- src/app/inbox/components/notification/notification.component.scss-theme.scss
- src/app/inbox/components/notification/notification.component.ts
- src/app/inbox/components/notifications/notifications.component.html
- src/app/types/notifications.endpoint.ts
https://trello.com/c/br5hHnmh/7155-qa-new-inbox-already-read-notifications-are-not-being-properly-shown
> add missing read state in notifications

- src/app/inbox/components/notification/notification.component.ts
https://trello.com/c/br5hHnmh/7155-qa-new-inbox-already-read-notifications-are-not-being-properly-shown
> fix notification delay

- src/app/cdk/platform-info/platform-info.service.ts
https://trello.com/c/rf8ziw3a/7184-critical-redirect-uris-with-the-word-social-result-in-a-call-to-the-wrong-endpoint
> fix oauth with the word social in the redirect uri

- src/app/layout/footer/footer.component.html
- src/app/layout/footer/footer.component.scss
https://trello.com/c/wOEl9GRF/7203-footer-missing-space-between-the-orcid-and-twitter-logos
> fix space between orcid and twitter logo

- src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.ts
Two issues fixed here: 
- When trying to edit on Funding, due to a null pointer execption, if id value or url were empty, the form doesn't display any external id value
- When the funding comes with one or more externa identifiers, the first one was always empty, because the array contains one empty element by default
> Fix error when loading the edit form the ext id value and url were empty

- src/app/record/components/work/work.component.html
@leomendoza123  the component has the preserve white spaces in ts but it doesn't preserve it if I don't explicitly add nbsp
> Fixed double spacing for translation title

- src/app/shared/validators/date/date.validator.ts
Apart from fixing the explorer error this PR will fix the following issue: 
BEFORE: 
When the start and end year are the same.  And the end month is defined, but the start month is not defined. 
The save button will close the modals but the item won't be updated. This applies for affiliations and fundings. 
NOW: 
The same error state of the old app will be shown, and the user can't save the form
> Improve date validatio

- src/app/core/search/search.service.ts
ROR ids start with http, we assume that if starts with http is a ror id and map it to ror-org-id in the institution name
> 7842 rors are included in search for the UI and the api 

- src/app/record/components/work/work.component.html
- src/app/record/components/work/work.component.scss
- src/app/record/components/work/work.component.ts
- src/app/shared/pipes/format-bibtex/format-bibtex.pipe.spec.ts
- src/app/shared/pipes/format-bibtex/format-bibtex.pipe.ts
- src/app/shared/shared.module.ts
- src/locale/properties/works/works.en.properties
- src/locale/properties/works/works.lr.properties
- src/locale/properties/works/works.rl.properties
- src/locale/properties/works/works.xx.properties
because citation-js is not a ESModule I had troubles resolving the dependencies properly. I reused the same library we already have in works to parse bibtex ( bibtex-parse-js ) and a pre tag.
> Added the hide reveal citations

- src/app/record/components/work/work.component.html
- src/app/record/components/work/work.component.scss
in the sub-header "Citation (citation-type)", the citation type should not be in bold. Here's an example of how it should be displayed: "Citation (bibtex)"
The link "switch to expanded formatting" comes right after the end of the citation. There should be a line break between the end of the citation and the link. As seen here: capture2-citation.jpg
When a user clicks the link "switch to expanded formatting", the text of the citation should wrap into the next line. Right not it overflows the screen. As seen in: capture1-citation.jpg
> Fixed the QA errors as detailed in the card

- src/app/record/components/work-contributor-role/work-contributor-roles.component.html
> fix: Capitalize contribution role options

- src/app/core/record-works/record-works.service.ts
- src/app/record/components/org-identifier/org-identifier.component.html
- src/app/record/components/work-stack-group/work-stack-group.component.ts
- src/app/shared/pipes/organization-link/organization-link.pipe.ts
> Fix/8202 grid stop displaying grid organisation identifiers as links in the UI

- src/app/record/components/work-contributor-role/work-contributor-roles.component.ts
> fix: Add default option if contributor is present but there is no role

- src/app/record/components/work-form/work-form/work-form.component.ts
> fix: Only add `rolesAndSequences` array if valid roles were selected

- src/app/record/components/work/work.component.html
- src/app/record/components/work/work.component.ts
> fix: Remove variable initialization in ngOnInit

- src/app/core/record-fundings/record-fundings.service.ts
[[QA] Endless loading bar under funding section in public page](https://trello.com/c/HuA8VIge/8235-qa-endless-loading-bar-under-funding-section-in-public-page)
> fix: Stop endless loading bar in funding section

- src/app/record/components/work-contributor-role/work-contributor-roles.component.ts
- src/app/shared/validators/unique/unique.validator.ts
> fix(work): Update unique validator to allow duplicated options

- CHANGELOG.md
- src/app/core/record-emails/record-emails.service.ts
- src/app/types/common.endpoint.ts
- src/app/types/record.endpoint.ts
I only used the extended date on the emails because the timestamps are only being returned in the emails endpoint
> create extended dates and add timestamps to emails
