ORCID/orcid-angular

src/app/home/components/news/news.component.html, src/app/home/components/news/news.component.scss
This reverts commit dbb2c15514ebeee1e83bfdbedb0e24d2b5df5b82.
=> Revert "Add margin to news loading spiner"

.dockerignore, Caddyfile, Dockerfile, docker-compose.yml
Initial backend with docker and caddy server
=> initial docker and docker-compose

src/app/layout/header/header.component.scss-theme.scss, src/app/layout/header/menu.ts, src/assets/scss/material.light-theme.scss, src/assets/scss/material.palettes.scss
- add grey color to the palette
=> Add active state to the nav menu

angular.json, src/app/layout/user-menu/user-menu.component.html
- add AOT compilation by default to local-en
=> Fix user menu url and uppercase button

src/app/home/pages/home/home.component.scss
This reverts commit d316b4f6bdf346b6803beddd87a496955179606f.
=> Revert "Fix hero banner height"

angular.json
more info https://github.com/angular/angular-cli/issues/15125
=> Fix safari ES6 modules to be request with credentials

src/app/password-recovery/pages/password-recovery/password-recovery.component.html
https://trello.com/c/RhtiIcJ9/6533-change-5-minutes-to-10-minutes-in-password-reset-message-05
=> fix message in recovery password

src/app/layout/user-menu/user-menu.component.html
https://trello.com/c/45iNZwhU/6523-critical-a11y-issue-on-the-new-homepage
=> fix a11y violation in homepage

src/app/layout/user-menu/user-menu.component.html
https://trello.com/c/45iNZwhU/6523-critical-a11y-issue-on-the-new-homepage
=> removing redundant attribute

src/app/password-recovery/pages/password-recovery/password-recovery.component.html, src/app/password-recovery/pages/password-recovery/password-recovery.component.ts
https://trello.com/c/nDJLV16V/6546-on-forgot-id-password-screen-preselect-password-05
=> password by default option in password recovery

src/app/core/sign-in/sign-in.service.ts, src/app/sign-in/components/two-factor/two-factor.component.ts
https://trello.com/c/GbBwBfeV/6678-login-service-imports-localhost-environment
=> Remove environment localhost and unused import

src/app/sign-in/pages/sign-in/sign-in.component.html
https://trello.com/c/s0aa2fu0/6673-orcid-angular-signin-user-email-id-validation
=> Add routerLink to reset-password

src/app/layout/header/header.component.html, src/app/layout/header/header.component.ts, src/app/layout/search/search.component.html, src/app/layout/search/search.component.ts
https://trello.com/c/TJ4ggAOL/6697-qa-signin-the-signin-register-button-is-not-hidden-in-the-signin-page
=> Hide signin button under the /signin route

src/app/constants.ts, src/app/core/sign-in/sign-in.service.ts, src/app/shared/validators/username/username.validator.ts
https://trello.com/c/Kf9ayPZ3/6699-qa-signin-unable-to-use-https-or-http-full-url-as-username
=> 6699 qa signin unable to use https or http full url as username

src/app/sign-in/components/errors/deactivated/deactivated.component.ts
https://trello.com/c/Rfo1mPsc/6708-qa-signin-while-reactivating-email-field-get-populated-with-orcid-id
=> Add autofill only for emails

src/app/sign-in/pages/sign-in/sign-in.component.ts
https://trello.com/c/zKYhxA97/6716-qa-signin-reactivate-message-should-be-hidden-if-user-clicks-sign-in-again
=> Hide errors when sign in attempt occurs

src/app/constants.ts, src/app/core/search/search.service.ts
https://trello.com/c/kjrf6tcV/6629-advance-search-doesnt-return-diacritics
=> Add given and family names to advanced search

src/assets/scss/material.typography.scss
https://trello.com/c/d7LJShWc/6695-qa-signin-placeholder-text-cutoff
=> Fix placeholder and mat label

src/app/sign-in/components/two-factor/two-factor.component.html
https://trello.com/c/pqKELiB7/6751-qa-2fa-auth-code-field-allows-browser-auto-complete
=> Disable autocomplete in two factor authentication

src/app/constants.ts, src/app/core/search/search.service.ts
Reverts ORCID/orcid-angular#183
https://trello.com/c/kjrf6tcV/6629-advance-search-doesnt-return-diacritics
=> Revert "Add given and family names to advanced search"

src/assets/scss/material.orcid.overwrites.scss/form-field-outline.scss, src/assets/scss/material.typography.scss
https://trello.com/c/d7LJShWc/6695-qa-signin-placeholder-text-cutoff?menu=filter&filter=member:danielpalafox7
=> Fix placeholder sign in, institutional

src/app/institutional/pages/institutional/institutional.component.html, src/app/institutional/pages/institutional/institutional.component.scss
https://trello.com/c/35k0FDZv/6781-qa-signin-institutional-signin-is-broken-in-ie11
=> Fix institutional sign in ie11

src/app/sign-in/components/social/social.component.html, src/app/sign-in/components/social/social.component.ts, src/app/sign-in/pages/sign-in/sign-in.component.html, src/assets/scss/material.orcid.overwrites.scss/_button-theme.scss, src/assets/scss/material.orcid.overwrites.scss/button.scss, src/assets/scss/material.orcid.overwrites.scss/card.scss
https://trello.com/c/5LsWFAl4/6759-qa-angular-signin-is-broken-on-ie11
=> fix ie11 sign error with svg icons

src/app/cdk/snackbar/snackbar.service.ts
Fix wrong toaster error color and position
=> Fix snackbar color

src/app/core/google-analytics/google-analytics.service.ts, src/environments/environment.local.tomcat.ts, src/environments/environment.local.ts, src/environments/environment.local.with.sandbox.ts, src/environments/environment.production.ts, src/environments/environment.qa.ts, src/environments/environment.sandbox.ts
=> Add GA testing evinromnet for QA

src/app/sign-in/pages/sign-in/sign-in.component.ts
https://trello.com/c/03K04N7u/6814-qa-signin-add-space-before-register-now-on-ie11
=> Fix whitespace in ie11

src/app/password-recovery/pages/password-recovery/password-recovery.component.html
https://trello.com/c/dkvx44K8/6810-qa-reset-password-labelled-as-access-through-your-institution
=> Fix password recovery title

src/app/sign-in/components/errors/deactivated/deactivated.component.html, src/app/sign-in/components/two-factor/two-factor.component.html, src/app/sign-in/sign-in.module.ts
https://trello.com/c/CUUJ6Ybe/6795-qa-signin-links-above-authenticate-button-are-not-in-the-tab-order
=> Fix a tag accessibility

src/app/register/components/form-personal/form-personal.component.ts, src/app/sign-in/components/errors/deactivated/deactivated.component.html, src/app/sign-in/components/errors/deactivated/deactivated.component.ts
https://trello.com/c/k12CjMDN/6802-qa-signin-issues-with-reactivate
=> Display error message from the backend

src/app/register/pages/register/register.component.ts
The only purpose of this PR is to add the TODO comment
=> Add TODO for unexpect validation errors

src/app/sign-in/pages/sign-in/sign-in.component.scss
https://trello.com/c/03K04N7u/6814-qa-signin-add-space-before-register-now-on-ie11
=> Removing margin sign in

src/app/register/components/form-personal/form-personal.component.html
Reverts ORCID/orcid-angular#255
=> Revert "Atemp to disable autocompletes on email confirmation"

src/app/sign-in/components/form-sign-in/form-sign-in.component.ts, src/app/sign-in/pages/sign-in/sign-in.component.ts
https://trello.com/c/LfCTI7Wu/6682-social-institutional-institutional-link-account-8
=> add username update in form sign in

src/app/app-routing.module.ts, src/app/core/user/user.service.ts, src/app/sign-in/components/social/social.component.scss-theme.scss
https://trello.com/c/xoTzzqSl/6675-signin-oauth-support
=> fix REAL_USER_ORCID missing, disable guard and fix google button

src/app/layout/header/header.component.html, src/app/layout/header/header.component.scss, src/app/layout/header/header.component.scss-theme.scss, src/app/layout/header/header.component.ts, src/app/layout/header/menu.ts, src/environments/environment.local.ts, src/environments/environment.local.with.sandbox.ts, src/environments/environment.production.ts, src/environments/environment.qa.ts, src/environments/environment.sandbox.ts
https://trello.com/c/OIlbX1qu/6829-registry-changes-needed-for-info-site-migration-5
=> fix new info menu

src/app/guards/oauth.guard.ts
https://trello.com/c/xoTzzqSl/6675-signin-oauth-support
=> fix force login

src/app/core/google-analytics/google-analytics.service.ts, src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
https://trello.com/c/m9cYTx3V/6676-signin-ga-events
=> add sign-in ga events

src/app/layout/footer/footer.component.ts, src/app/layout/header/header.component.ts, src/environments/environment.local.ts, src/environments/environment.local.with.sandbox.ts, src/environments/environment.production.ts, src/environments/environment.sandbox.ts
https://trello.com/c/OIlbX1qu/6829-registry-changes-needed-for-info-site-migration-5
=> fix info site production

src/app/guards/oauth.guard.ts
https://trello.com/c/xoTzzqSl/6675-signin-oauth-support
=> fix missing params in oauth

src/locale/properties/signin/signin.cs.properties, src/locale/properties/signin/signin.es.properties, src/locale/properties/signin/signin.fr.properties, src/locale/properties/signin/signin.ja.properties
https://trello.com/c/IT6G3MLa/6749-qa-reactivation-message-replace-url-with-link-text
=> remove inaccurate translations

src/app/layout/header/header.component.scss-theme.scss, src/app/layout/header/header.component.ts
https://trello.com/c/TUmQgDVf/6865-font-size-on-the-qa-site-new-navigation-is-14px-on-prod-is-18px
=> fix font size header menu

.gitignore, .tx/config
This PR is NOT REQUIRE before requesting the translations for all the current strings
=> Add missing translation configs

src/app/constants.ts, src/app/password-recovery/pages/password-recovery/password-recovery.component.ts, src/app/shared/validators/username/username.validator.ts, src/app/sign-in/components/errors/deactivated/deactivated.component.ts, src/app/validators.ts
https://trello.com/c/UaMfVkyX/6918-remove-pattern-validation-on-signing-reset-password-reactivate-and-claim-pages
=> fix email validator in signing, reset-password and reactivate

src/app/app-routing.module.ts, src/app/core/disco/disco.service.ts, src/app/guards/link-account.guard.ts, src/app/institutional/pages/institutional/institutional.component.ts
https://trello.com/c/GlabNeGV/6932-qa-institutional-sign-in-doesnt-work
=> fix Link guard and improve institutional autocomplete

src/app/cdk/platform-info/platform-info.service.ts, src/app/link-account/pages/link-account/link-account.component.html, src/app/link-account/pages/link-account/link-account.component.ts
https://trello.com/c/39YA1RU8/6933-qa-register-go-back-button-text-is-hardcoded
=> fix register button when cancel link account button it is clicked

src/app/sign-in/components/social/social.component.html
https://trello.com/c/4qVPfo0V/6931-qa-sign-in-with-facebook-doesnt-work
=> fix sign in Facebook

src/app/link-account/pages/link-account/link-account.component.html
https://trello.com/c/LfCTI7Wu/6682-social-institutional-institutional-link-account-8
=> fix institution and name must be bold

src/app/institutional/pages/institutional/institutional.component.html
https://trello.com/c/oYhOWe2a/6949-qa-institutional-signin-enter-selects-org-from-dropdown-enter-deletes-org
=> fix institutional sign in erase institution when enter is pressed

src/app/app.component.ts
https://trello.com/c/glpQErep/6953-qa-disable-help-widget-in-the-authorize-screen
=> fix disable widget in oauth

.tx/config, src/app/app-routing.module.ts, src/app/constants.ts, src/app/core/oauth/oauth.service.ts, src/app/sign-in/sign-in.module.ts, src/app/two-factor/pages/two-factor/two-factor.component.html, src/app/two-factor/pages/two-factor/two-factor.component.scss, src/app/two-factor/pages/two-factor/two-factor.component.spec.ts, src/app/two-factor/pages/two-factor/two-factor.component.ts, src/app/two-factor/two-factor-routing.module.ts, src/app/two-factor/two-factor.module.ts, src/app/types/two-factor.endpoint.ts, src/locale/i18n.pseudo.component.html, src/locale/properties/two-factor/two-factor.ar.properties, src/locale/properties/two-factor/two-factor.cs.properties, src/locale/properties/two-factor/two-factor.en.properties, src/locale/properties/two-factor/two-factor.es.properties, src/locale/properties/two-factor/two-factor.fr.properties, src/locale/properties/two-factor/two-factor.it.properties, src/locale/properties/two-factor/two-factor.ja.properties, src/locale/properties/two-factor/two-factor.ko.properties, src/locale/properties/two-factor/two-factor.lr.properties, src/locale/properties/two-factor/two-factor.pt.properties, src/locale/properties/two-factor/two-factor.rl.properties, src/locale/properties/two-factor/two-factor.ru.properties, src/locale/properties/two-factor/two-factor.xx.properties, src/locale/properties/two-factor/two-factor.zh_CN.properties, src/locale/properties/two-factor/two-factor.zh_TW.properties
https://trello.com/c/L1WNUVfT/6758-add-new-page-link-shibboleth-signin-for-new-institutional-linking-orcid-angular
=> add 2fa page missing in institutional sign in

src/app/sign-in/components/form-sign-in/form-sign-in.component.ts, src/app/sign-in/components/two-factor/two-factor.component.ts, src/app/two-factor/pages/two-factor/two-factor.component.ts
https://trello.com/c/ra4dSqMO/6969-qa-unable-to-enter-2fa-authentication-code-after-attempting-an-incorrect-recovery-code
=> fix 2fa after invalid recovery code is send

src/app/institutional/pages/institutional/institutional.component.html, src/app/institutional/pages/institutional/institutional.component.scss, src/app/institutional/pages/institutional/institutional.component.ts, src/locale/properties/institutional/institutional.ar.properties, src/locale/properties/institutional/institutional.cs.properties, src/locale/properties/institutional/institutional.en.properties, src/locale/properties/institutional/institutional.es.properties, src/locale/properties/institutional/institutional.fr.properties, src/locale/properties/institutional/institutional.it.properties, src/locale/properties/institutional/institutional.ja.properties, src/locale/properties/institutional/institutional.ko.properties, src/locale/properties/institutional/institutional.lr.properties, src/locale/properties/institutional/institutional.pt.properties, src/locale/properties/institutional/institutional.rl.properties, src/locale/properties/institutional/institutional.ru.properties, src/locale/properties/institutional/institutional.uk.properties, src/locale/properties/institutional/institutional.xx.properties, src/locale/properties/institutional/institutional.zh_CN.properties, src/locale/properties/institutional/institutional.zh_TW.properties
https://trello.com/c/bB6mJQxS/6950-qa-institutional-signin-missing-use-a-suggested-selection
=> add missing use a suggested selection in institutional sign in

src/app/cdk/form-directives/trim.directive.ts, src/app/register/components/form-personal/form-personal.component.ts, src/app/shared/validators/username/username.validator.ts, src/app/sign-in/components/form-sign-in/form-sign-in.component.html, src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
https://trello.com/c/FIqHqhej/6966-qa-clicking-register-now-on-signin-makes-username-field-red
=> fix register/sign form input red

src/app/types/request-info-form.endpoint.ts
https://trello.com/c/KcRRjHlj/6947-oauth-authorize-broken-for-open-id-implicit-flow
=> add missing error in request infor form

src/app/core/oauth/oauth.service.ts, src/app/two-factor/pages/two-factor/two-factor.component.ts
https://trello.com/c/YygN3r2J/6976-qa-google-facebook-signin-goes-to-old-app-2fa
=> fix social 2fa sign in

src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
https://trello.com/c/8sT8rX90/6988-qa-social-signin-not-working
=> fix qa social sign in not working

src/app/core/oauth/oauth.service.ts, src/app/core/user/user.service.ts, src/app/guards/language.guard.ts, src/app/sign-in/components/form-sign-in/form-sign-in.component.ts, src/app/sign-in/pages/sign-in/sign-in.component.html, src/app/sign-in/pages/sign-in/sign-in.component.ts
https://trello.com/c/iSUv9J0S/6886-speedup-oauth-custom-initjson-error-management
=> fix custom errors

src/app/institutional/pages/institutional/institutional.component.html, src/app/institutional/pages/institutional/institutional.component.scss
https://trello.com/c/NN4EHT8w/6982-qa-institutional-linking-go
=> fix institutional go back button

src/app/guards/sign-in.guard.ts
https://trello.com/c/5fQe8P5w/6977-qa-showloginshould-be-ignored-if-url-contains-email-or-orcid-parameter
=> fix ignore show_login

src/app/guards/sign-in.guard.ts, src/app/register/pages/register/register.component.ts, src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
https://trello.com/c/JtrmQdPf/7018-qa-temp
=> fix account linking and registration

src/app/core/disco/disco.service.ts
https://trello.com/c/syS5Qpl0/7012-qa-auto-complete-at-institutional-signin
=> fix autocomplete institutional

src/app/institutional/pages/institutional/institutional.component.ts
https://trello.com/c/bB6mJQxS/6950-qa-institutional-signin-missing-use-a-suggested-selection
=> fix saml cookie

src/app/institutional/pages/institutional/institutional.component.ts
https://trello.com/c/pKtclJ1a/7025-qa-sandbox-institutional-signin-not-working
=> renaming institutional cookie

src/app/layout/header/header.component.scss
https://trello.com/c/OIlbX1qu/6829-registry-changes-needed-for-info-site-migration-5
=> fix mobile menu

src/app/sign-in/components/social/social.component.html, src/app/sign-in/components/social/social.component.ts, src/locale/i18n.pseudo.component.html
https://trello.com/c/T391QRdO/6984-qa-a11y-on-signin-screen-reader-reads-signin-icons
=> add aria-label attribute to institutional and social buttons

src/app/institutional/pages/institutional/institutional.component.scss, yarn.lock
https://trello.com/c/TG57bgh9/7044-add-margin-bottom-to-institutional-logo
=> add margin to institutional logo and add missing yarn lock updated file

src/app/guards/authorize.guard.ts
Fix response type as a parameter in the redirect url
=> fix response type as parameter

src/app/guards/authorize.guard.ts
fix stripping query parameters in OAuth request
=> fix stripping query parameters and removing unused imports

src/app/cdk/info-drop-down/info-drop-down.component.scss, src/app/register/components/step-a/step-a.component.ts
https://trello.com/c/2Z3OPn6O/7033-qa-sandbox-oauth-org-extra-info-panel-breaks-mid-word
=> fix breaks mid-word authorize view

src/app/cdk/pannel/panel/panel.component.html, src/app/cdk/pannel/panel/panel.component.scss, src/app/cdk/pannel/panel/panel.component.ts, src/app/record/components/side-bar/side-bar.component.html, src/app/types/record.endpoint.ts
https://trello.com/c/zs9cUIsw/7064-handle-empty-sidebar-containers
=> fix empty sidebar containers

src/app/guards/sign-in.guard.ts
https://trello.com/c/qrsCFitY/7092-the-register-is-shown-on-promptlogin-requests-for-logged-in-users
=> fix oauth email parameter not working

src/app/core/oauth/oauth.service.ts
https://trello.com/c/kM6aYdoj/7050-invalid-requestinfoform-endpoint-response
=> fix invalid request info form request

cypress/integration/google-analytics.e2e.js, cypress/integration/oauth-life-cycles.e2e.js, cypress/support/google-analytics.commands.js, src/app/constants.ts, src/app/core/register/register.service.ts, src/app/core/user/user.service.ts, src/app/guards/authorize.guard.ts, src/app/register/pages/register/register.component.ts
https://trello.com/c/gtZWRa4W/7107-issue-with-urls-that-are-redirect-to-the-oauth-page
=> fix url that are redirected to the oauth

src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
=> Test to fix firefox autofill

src/app/inbox/components/notification/notification.component.scss-theme.scss, src/assets/scss/material.light-theme.scss, src/assets/scss/material.palettes.scss
https://trello.com/c/4FjSoDKP/7163-qa-new-inbox-a11y-violation-orange-color-for-permissions
=> fix a11y color in permissions

src/app/core/inbox/inbox.service.ts, src/app/inbox/components/notifications/notifications.component.html, src/app/inbox/components/notifications/notifications.component.ts, src/app/search/pages/search/search.component.html, src/app/search/search.module.ts, src/app/shared/components/showing-of/showing-of.component.html, src/app/shared/components/showing-of/showing-of.component.scss, src/app/shared/components/showing-of/showing-of.component.spec.ts, src/app/shared/components/showing-of/showing-of.component.ts, src/app/shared/shared.module.ts
https://trello.com/c/agQwbmIU/7154-qa-new-inbox-missing-item-range-showing-xx-of-xx
=> add missing showing of in inbox

src/app/inbox/components/notifications/notifications.component.ts
https://trello.com/c/FQve7LRi/7164-qa-new-inbox-forgets-to-keep-archived-notifications-hidden
=> change archive notifications behaviour

src/app/inbox/components/notification/notification.component.ts
https://trello.com/c/hFXVe0UG/7169-the-notifications-are-frozen-after-readig-and-closing
=> fix notifications doesnt open again

src/app/inbox/components/notification/notification.component.scss-theme.scss, src/assets/scss/material.light-theme.scss, src/assets/scss/material.palettes.scss
https://trello.com/c/br5hHnmh/7155-qa-new-inbox-already-read-notifications-are-not-being-properly-shown
=> fix read archived notifications

src/app/cdk/panel/panels/panels.component.ts, src/app/record/components/affiliation-stacks-groups/affiliation-stacks-groups.component.html, src/app/record/components/affiliation-stacks-groups/affiliation-stacks-groups.component.ts, src/app/record/components/funding-stacks-groups/funding-stacks-groups.component.html, src/app/record/components/funding-stacks-groups/funding-stacks-groups.component.ts, src/app/record/components/peer-reviews/peer-reviews.component.html, src/app/record/components/peer-reviews/peer-reviews.component.ts, src/app/record/components/research-resources/research-resources.component.html, src/app/record/components/research-resources/research-resources.component.ts, src/app/record/components/work-stack-group/work-stack-group.component.html, src/app/record/components/work-stack-group/work-stack-group.component.ts, src/app/record/pages/my-orcid/my-orcid.component.html, src/app/record/pages/my-orcid/my-orcid.component.ts
=> fix disable/enable buttons when panels are close/expand manually

src/app/cdk/panel/panel-data-line/panel-data-line.component.html, src/app/record/components/display-external-ids/display-external-ids.component.html
=> fix prefix in works

src/app/record/components/research-resources/research-resources.component.html
=> fix add missing part of in research resources

src/app/record/components/peer-reviews/peer-reviews.component.html
=> fix add missing part of in peer reviews

src/app/record/components/funding/funding.component.html
=> fix hide contributors title if there is no contributors to display

src/app/record/components/research-resources/research-resources.component.html
=> fix clicklabe source in research resources

src/app/record/components/affiliation/affiliation.component.html, src/app/record/components/research-resources/research-resources.component.html
=> fix source type

src/app/record/components/peer-reviews/peer-reviews.component.html
=> fix peer review source shouldnt be clickable

src/app/record/components/peer-reviews/peer-reviews.component.html
=> remove added and last modified date in peer reviews and fix some errors

src/app/record/components/top-bar/top-bar.component.html, src/app/record/components/top-bar/top-bar.component.scss, src/app/record/components/top-bar/top-bar.component.scss-theme.scss, src/app/record/components/top-bar/top-bar.component.ts
=> fix names panels

src/app/record/components/funding/funding.component.html
=> fix funding region and city

src/app/record/components/top-bar/top-bar.component.ts
=> fix printable version button

src/app/cdk/panel/panel/panel.component.scss-theme.scss, src/app/record/components/peer-reviews/peer-reviews.component.html, src/app/record/components/peer-reviews/peer-reviews.component.scss, src/app/record/components/peer-reviews/peer-reviews.component.scss-theme.scss, src/app/record/components/research-resources/research-resources.component.html, src/app/record/components/research-resources/research-resources.component.scss, src/app/record/components/research-resources/research-resources.component.scss-theme.scss, src/assets/scss/material.light-theme.scss, src/assets/scss/material.palettes.scss
=> fix research resources border and panels color in public page

src/app/cdk/side-bar/modals/modal-country/modal-country.component.html, src/app/cdk/side-bar/modals/modal-country/modal-country.component.ts, src/app/cdk/side-bar/modals/modal-keyword/modal-keyword.component.html, src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.html, src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.scss, src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.ts, src/app/cdk/side-bar/modals/modal-websites/modal-websites.component.html, src/app/cdk/side-bar/modals/modal-websites/modal-websites.component.ts, src/app/record/components/research-resource/research-resource.component.html
=> fix Websites & social links date format

src/app/cdk/modal/modal/modal.component.html
=> fix: remove gaps in modal footer and side bar

src/app/cdk/panel/panel-source/panel-source.component.scss
=> fix: misaligned source in activities

src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.html
=> fix: date fields order in affiliations

src/app/cdk/panel/panel/panel.component.html, src/app/cdk/panel/panel/panel.component.ts, src/app/record/components/affiliation-stack/affiliation-stack.component.html, src/app/record/components/funding-stack/funding-stack.component.html, src/app/record/components/work-stack/work-stack.component.html
=> fix: copy/edit functionality doesnt have to be show in certain cases

src/app/cdk/modal/modal-side-bar/modal-side-bar.component.html
=> fix: quick nav styling in modals

src/app/cdk/modal/modal-header/modal-header.component.html, src/app/cdk/side-bar/modals/modal-email/modal-email.component.html, src/app/cdk/side-bar/modals/modal-keyword/modal-keyword.component.html, src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.html, src/app/cdk/side-bar/modals/modal-websites/modal-websites.component.html, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.html, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.scss-theme.scss, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.html, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.scss-theme.scss, src/app/record/components/search-link-wizard/search-link-wizard.component.html, src/app/record/components/top-bar/modals/modal-biography/modal-biography.component.html, src/app/record/components/top-bar/modals/modal-biography/modal-biography.component.scss-theme.scss, src/app/record/components/top-bar/modals/modal-name/modal-name.component.html, src/app/record/components/work-modal/work-modal.component.html, src/app/record/components/work-modal/work-modal.component.scss-theme.scss, src/app/record/components/work/modals/works-visibility-modal/works-visibility-modal.component.html
=> fix: font size in modals

src/app/cdk/modal/modal/modal.component.scss, src/app/cdk/modal/modal/modal.component.scss-theme.scss
=> fix: modal border

src/app/record/components/peer-review-stacks-groups/peer-review-stacks-groups.component.html, src/app/record/components/peer-review-stacks-groups/peer-review-stacks-groups.component.ts
=> fix: after sorting keep panel open in peer reviews section

src/app/core/record-affiliations/record-affiliations.service.ts, src/app/core/record-fundings/record-fundings.service.ts, src/app/core/record-peer-review/record-peer-review.service.ts, src/app/core/record-research-resource/record-research-resource.service.ts, src/app/record/components/affiliation-stack/affiliation-stack.component.ts, src/app/record/components/funding-stack/funding-stack.component.ts, src/app/record/components/peer-review-stack/peer-review-stack.component.ts, src/app/record/components/research-resource-stack/research-resource-stack.component.ts
=> fix: mark as missing primary source functionality in activities

src/app/cdk/side-bar/modals/modal-country/modal-country.component.ts, src/app/cdk/side-bar/modals/modal-keyword/modal-keyword.component.ts, src/app/cdk/side-bar/modals/modal-websites/modal-websites.component.ts, src/app/record/components/top-bar/modals/modal-name/modal-name.component.ts
=> fix: items added by the API are been removed

src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.html
=> fix: end date format

src/app/constants.ts, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.html, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.ts, src/app/record/components/work-external-identifiers-edit/work-external-identifiers-edit.component.html, src/app/record/components/work-external-identifiers-edit/work-external-identifiers-edit.component.ts, src/app/record/components/work-form/work-form/work-form.component.html, src/app/record/components/work-form/work-form/work-form.component.ts, src/locale/properties/funding/funding.en.properties, src/locale/properties/funding/funding.lr.properties, src/locale/properties/funding/funding.rl.properties, src/locale/properties/funding/funding.xx.properties, src/locale/properties/shared/shared.en.properties, src/locale/properties/shared/shared.lr.properties, src/locale/properties/shared/shared.rl.properties, src/locale/properties/shared/shared.xx.properties
=> fix: description is required and it shouldnt and fix placeholders

src/app/record/components/affiliation-stacks-groups/affiliation-stacks-groups.component.html, src/app/types/record-affiliation.endpoint.ts
=> fix: editing a distinction was changed it to invited position

src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.ts
=> fix: rm unnecessary code

src/app/record/components/funding-stacks-groups/modals/modal-funding-search-link/modal-funding-search-link.component.html
=> fix: link in modal funding

src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.html, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.scss
=> fix hidden translation title if has content

src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.html, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.scss, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.ts, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.html, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.scss, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.ts, src/app/shared/validators/date/date.validator.ts
=> fix: input date group error message

src/app/record/components/modals/modal-delete-item/modal-delete-items.component.html, src/app/record/components/modals/modal-delete-item/modal-delete-items.component.scss
=> add missing obo member source missing and fix style description border

src/app/cdk/side-bar/modals/modal-email/modal-email.component.html
=> fix: disabled input to edit non primary email verified

src/app/record/components/work-stack-group/modals/work-bibtex-modal/work-bibtex-modal.component.html
@leomendoza123  it is missing the part  to transform the external ID in a URL
=> Added external Ids to bibtex modal

src/app/cdk/panel/panels/panels.component.html, src/app/cdk/panel/panels/panels.component.ts, src/app/record/components/peer-review-stacks-groups/peer-review-stacks-groups.component.html, src/app/record/components/peer-review-stacks-groups/peer-review-stacks-groups.component.ts, src/app/shared/validators/environment-check/environment-check.ts
Hide peer review section if no reviews.  Do not display Add button for peer reviews
=> Peer review fixes

src/app/record/components/peer-review-stacks-groups/peer-review-stacks-groups.component.ts
=> check for undefined instead of empty to emit event when last review is deleted and the array is empty

src/app/constants.ts
Require https://github.com/ORCID/ORCID-Source/pull/6388
=> Enable # and sync url validator with backend validator

.gitignore, cypress/support/signin.commands.js
A fix on the .gitignore file and a cleanup on the signin command file
=> Code cleanup

.gitignore, package.json
couple of tweaks to help with running in a container
=> Dockerization

src/app/cdk/side-bar/modals/modal-country/modal-country.component.html, src/app/cdk/side-bar/modals/modal-email/modal-email.component.html, src/app/layout/header/header.component.html, src/app/layout/language/language.component.html, src/app/layout/search/search.component.html, src/app/layout/user-menu/user-menu.component.html
As specified in the scope of https://trello.com/c/WjQ0kRQi/7978-automation-support-adding-id-to-web-elements
=> Added support for the required fields for automation

src/app/account-settings/components/settings-actions-deactivate/settings-actions-deactivate.component.ts, src/app/app-routing.module.ts, src/app/constants.ts, src/app/layout/header/header.component.ts, src/app/layout/user-menu/user-menu.component.ts, src/app/two-factor-setup/components/two-factor-recovery-codes/two-factor-recovery-codes.component.html
Require:
https://github.com/ORCID/orcid-reg-docker-private/pull/2
https://github.com/ORCID/orcid-ansible_inventory-private/pull/98
=> Remove QA from app route (account settings) 

cypress/integration/my-orcid/add-employment.e2e.js, package.json, yarn.lock
Updated cypress version, add employment script
=> Updated cypress version, add employment script

cypress/helpers/uniqueEntry.js, cypress/integration/my-orcid/add-education-education.e2e.js, cypress/integration/my-orcid/add-education-qualification.e2e.js, cypress/integration/my-orcid/add-employment.e2e.js
add education and qualification, new helper and updated add employment
=> add education and qualification, new helper and updated add employment

cypress/integration/registry/reset-password-recover-id.e2e.js
scripts to reset passw and recover id
=> scripts to reset passw and recover id

cypress/integration/my-orcid/add-invited-positions-distinctions.e2e.js, cypress/integration/my-orcid/add-invited-positions.e2e.js
scripts to add invited positions and distinctions
=> scripts to add invited positions and distinctions

cypress/integration/my-orcid/add-membership-service.e2e.js, cypress/integration/my-orcid/add-membership.e2e.js
scripts my orcid adding membership and service data
=> scripts my orcid adding membership and service data

src/app/account-trusted-parties/components/settings-trusted-individuals-search/settings-trusted-individuals-search.component.ts, src/app/types/search.endpoint.ts
REQUIRE: https://github.com/ORCID/ORCID-Source/pull/6531
=> 8079 trusted parties current trusted individuals do not appear in trusted individuals search

src/app/types/works.endpoint.ts, src/locale/properties/works/works.en.properties, src/locale/properties/works/works.lr.properties, src/locale/properties/works/works.rl.properties, src/locale/properties/works/works.xx.properties
Not to be merged until the orcid-model is published
=> Added review work type

src/app/register/pages/register/register.component.ts
=> fix: Don't display `is this you modal` while reactivating an account

src/app/record/components/work-contributors/work-contributors.component.ts
=> fix: Display all the affiliations that don't have an end date

src/app/record/components/work-contributor-role/work-contributor-roles.component.html, src/app/record/components/work-contributor-role/work-contributor-roles.component.ts
=> fix: Tab focus on new contributor role select

src/app/record/components/work-contributors/work-contributors.component.ts
=> fix: Commas separating affiliations in works

src/app/record/components/work-contributor-role/work-contributor-roles.component.ts
=> fix: Set `no specified role` by default to new roles

src/app/record/components/work-contributor-role/work-contributor-roles.component.html, src/app/record/components/work-contributor-role/work-contributor-roles.component.ts
=> fix: Remove delete button from first contributor role select

src/app/core/oauth/oauth.service.ts, src/app/core/user-info/user-info.service.ts
=> fix-orcid-parameter-unexpected-r

src/app/constants-country-codes.ts
https://trello.com/c/io7kmhJA/8340-qa-kosovo-as-country-of-publication-not-displayed-in-work-detailed-view
https://trello.com/c/oyD6XOUD/8339-qa-kosovo-not-displayed-in-countries-section-on-sidebar
=> Added Kosovo to the country names to country codes

cypress.config.ts, cypress/e2e/inbox_notifications/funding-inbox-notif.cy.js, cypress/e2e/my-orcid/add-bio.cy.js, cypress/e2e/my-orcid/add-peer-review.cy.js, cypress/e2e/my-orcid/add-publish-name.cy.js, cypress/e2e/my-orcid/add-work-manually.cy.js, cypress/e2e/my-orcid/public-page-visibility-public-affiliations.cy.js, cypress/e2e/my-orcid/sidebar-add-country.cy.js, cypress/e2e/my-orcid/sidebar-add-emails.cy.js, cypress/e2e/my-orcid/sidebar-add-keywords.cy.js, cypress/e2e/my-orcid/sidebar-add-websites-negative-testing.cy.js, cypress/e2e/my-orcid/sidebar-add-websites.cy.js, cypress/e2e/my-orcid/sidebar-change-visibility-primary-email.cy.js, cypress/e2e/my-orcid/verify-research-resources.cy.js, cypress/e2e/my-orcid/works-visibility-inconsistency-clientA-and-clientB.cy.js, cypress/e2e/my-orcid/works-visibility-inconsistency-owner-and-clientA.cy.js, cypress/e2e/registry/account-settings-visibility.cy.js, cypress/e2e/registry/email-verification-reminder.cy.js, cypress/e2e/registry/new-user-registration.cy.js, cypress/fixtures/inbox-notif-fixtures/funding-inbox-notif.fixture.json, cypress/fixtures/inboxNotif-users.fixture.json
also updated selectors in sidebar and registry scripts required after changes to ids/class updates required for the accessibility cards
=> inbox notif funding script

src/app/layout/search/search.component.scss-theme.scss, src/assets/scss/material.orcid.overwrites.scss/form-field.scss
After moving the code to the overwrite directory, the color was not applied.  This commit contains the fix for it.
=> Removed the ::ng-deep was causing the color not to be applied and added the placeholder color for search

cypress/e2e/contributors/manually-add-contributor-credit-role.cy.js
will upload a sample fixture file with user data with the next PR
=> Manually add work setting credit role for record owner

src/app/core/google-tag-manager/google-tag-manager.service.ts, src/app/guards/authorize.guard.ts
=> remove-4-second-wait-for-ublock-users

src/app/record/components/top-bar-verification-email/top-bar-verification-email.component.html, src/app/record/components/top-bar-verification-email/top-bar-verification-email.component.ts, src/app/record/components/top-bar/top-bar.component.html, src/app/record/pages/my-orcid/my-orcid.component.ts
(cherry picked from commit d4b25dd656168e98a507295e826e42aaca457b53)
=> 8565-email-verification-notice-not-displayed-at-the-top-of-a-record

src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.html, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.scss, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.scss-theme.scss, src/app/record/components/affiliation-stacks-groups/modals/modal-affiliations/modal-affiliations.component.ts, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.html, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.scss-theme.scss, src/app/record/components/funding-stacks-groups/modals/modal-funding/modal-funding.component.ts, src/locale/properties/record/record.en.properties, src/locale/properties/shared/shared.en.properties
This reverts commit ce5b11291d837229a1824d189332ec80e0f62f0e.
=> Rollback: feature/9168-update-affiliation-and-funding-typeahead-behaviours

src/app/account-trusted-parties/components/settings-users-that-thrust-you/settings-users-that-thrust-you.component.html, src/app/cdk/top-bar-my-public-record-preview/top-bar-my-public-record-preview/top-bar-my-public-record-preview.component.html, src/app/cdk/top-bar-my-public-record-preview/top-bar-my-public-record-preview/top-bar-my-public-record-preview.component.ts, src/app/layout/footer/footer.component.scss
footer css for mobile devices smaller then 400
top bar updated when revoking own permission
revoke own permission  button displayed in mobile devices
=> UI fixes for revoke own permission

src/app/core/login-interstitials/login-interstitials.service.ts
e.g. when you make all domains private and you've never seen the interstitial, you will need to refresh to see it instead of it appearing immediately
=> do not show interstitial until a refresh is made

src/app/cdk/panel/panel/panel.component.html, src/app/cdk/panel/panel/panel.component.scss, src/app/cdk/panel/panel/panel.component.ts, src/app/core/record-works/record-works.service.spec.ts, src/app/core/record-works/record-works.service.ts, src/app/core/record/record.service.ts, src/app/record/components/work-featured-stack-group/work-featured-stack-group.component.html, src/app/record/components/work-featured-stack-group/work-featured-stack-group.component.ts, src/app/record/components/work-featured/work-featured.component.html, src/app/record/components/work-featured/work-featured.component.scss, src/app/record/components/work-featured/work-featured.component.scss-theme.scss, src/app/record/components/work-featured/work-featured.component.spec.ts, src/app/record/components/work-featured/work-featured.component.ts, src/app/record/components/work-stack/work-stack.component.html, src/app/record/components/work-stack/work-stack.component.ts, src/app/record/record.module.ts, src/app/types/record-works.endpoint.ts, src/app/types/record.local.ts
there is now a separate endpoint for fetching featured works which is not relying on pages and groups -- an array of works is returned instead
as a result a new component had to be introduced instead of using the existing logic for displaying works
=> ${PD-1920} refactor feature works section

src/app/record/components/work-featured-stack-group/work-featured-stack-group.component.html, src/app/record/components/work-featured-stack-group/work-featured-stack-group.component.ts
featured works section gets updated when the last featured item is deleted
featured works section displayed when empty
=> ${PD-1988} fix featured works display states
